<?php

/**
 * @file
 * Hook implementations for the MassTimes Widget module.
 */

/**
 * Implements hook_theme().
 */
function masstimes_widget_theme(array $existing, string $type, string $theme, string $path): array {
  $module_path = \Drupal::moduleHandler()->getModule('masstimes_widget')->getPath();
  return [
    'masstimes_map' => [
      'variables' => ['settings' => NULL],
      'template'  => 'masstimes-map',
      'path'      => $module_path . '/templates',
    ],
  ];
}
